In [1]:
# Dependencies
import pandas as pd

In [2]:
# List of CSV files that need to be combined
files08 = ['data/201906-citibike-tripdata.csv', 'data/201907-citibike-tripdata.csv', 'data/201908-citibike-tripdata.csv', 'data/201909-citibike-tripdata.csv',
           'data/201910-citibike-tripdata.csv', 'data/201911-citibike-tripdata.csv', 'data/201912-citibike-tripdata.csv']

# Create an empty list to store each dataframe
df08_list = []

# Loop through each file in the list
for file in files08:
    # Read the file into a dataframe
    df08 = pd.read_csv(file)

    # Append the dataframe to the list
    df08_list.append(df08)

# Combine all the dataframes in the list into one dataframe
df08 = pd.concat(df08_list)

# Display dataframe
df08

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,330,2019-06-01 00:00:01.5000,2019-06-01 00:05:31.7600,3602.0,31 Ave & 34 St,40.763154,-73.920827,3570.0,35 Ave & 37 St,40.755733,-73.923661,20348,Subscriber,1992,1
1,830,2019-06-01 00:00:04.2400,2019-06-01 00:13:55.1470,3054.0,Greene Ave & Throop Ave,40.689493,-73.942061,3781.0,Greene Av & Myrtle Av,40.698568,-73.918877,34007,Subscriber,1987,2
2,380,2019-06-01 00:00:06.0190,2019-06-01 00:06:26.7790,229.0,Great Jones St,40.727434,-73.993790,326.0,E 11 St & 1 Ave,40.729538,-73.984267,20587,Subscriber,1990,2
3,1155,2019-06-01 00:00:06.7760,2019-06-01 00:19:22.5380,3771.0,McKibbin St & Bogart St,40.706237,-73.933871,3016.0,Kent Ave & N 7 St,40.720368,-73.961651,33762,Subscriber,1987,1
4,1055,2019-06-01 00:00:07.5200,2019-06-01 00:17:42.5580,441.0,E 52 St & 2 Ave,40.756014,-73.967416,3159.0,W 67 St & Broadway,40.774925,-73.982666,31290,Subscriber,1973,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955205,93,2019-12-31 23:58:18.0160,2019-12-31 23:59:51.6360,3141.0,1 Ave & E 68 St,40.765005,-73.958185,3142.0,1 Ave & E 62 St,40.761227,-73.960940,28734,Subscriber,1985,2
955206,786,2019-12-31 23:58:59.8960,2020-01-01 00:12:06.3460,490.0,8 Ave & W 33 St,40.751551,-73.993934,513.0,W 56 St & 10 Ave,40.768254,-73.988639,41418,Subscriber,1991,1
955207,351,2019-12-31 23:59:03.6950,2020-01-01 00:04:54.8730,3349.0,Grand Army Plaza & Plaza St West,40.672968,-73.970880,3368.0,5 Ave & 3 St,40.672815,-73.983524,27746,Subscriber,1935,2
955208,1571,2019-12-31 23:59:21.3610,2020-01-01 00:25:32.9420,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,366.0,Clinton Ave & Myrtle Ave,40.693261,-73.968896,28506,Subscriber,1980,1
955209,310,2019-12-31 23:59:55.2960,2020-01-01 00:05:05.7270,3351.0,E 102 St & 1 Ave,40.786995,-73.941648,3379.0,E 103 St & Lexington Ave,40.790305,-73.947558,21013,Subscriber,1969,0

In [3]:
# Dictionary mapping values in the 'gender' column to new values
mapping = {0: 'Unknown', 1: 'Male', 2: 'Female'}

# Use the 'map' method to change the values in the 'gender' column
df08['gender'] = df08['gender'].map(mapping)

# Show DataFrame
df08

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,330,2019-06-01 00:00:01.5000,2019-06-01 00:05:31.7600,3602.0,31 Ave & 34 St,40.763154,-73.920827,3570.0,35 Ave & 37 St,40.755733,-73.923661,20348,Subscriber,1992,Male
1,830,2019-06-01 00:00:04.2400,2019-06-01 00:13:55.1470,3054.0,Greene Ave & Throop Ave,40.689493,-73.942061,3781.0,Greene Av & Myrtle Av,40.698568,-73.918877,34007,Subscriber,1987,Female
2,380,2019-06-01 00:00:06.0190,2019-06-01 00:06:26.7790,229.0,Great Jones St,40.727434,-73.993790,326.0,E 11 St & 1 Ave,40.729538,-73.984267,20587,Subscriber,1990,Female
3,1155,2019-06-01 00:00:06.7760,2019-06-01 00:19:22.5380,3771.0,McKibbin St & Bogart St,40.706237,-73.933871,3016.0,Kent Ave & N 7 St,40.720368,-73.961651,33762,Subscriber,1987,Male
4,1055,2019-06-01 00:00:07.5200,2019-06-01 00:17:42.5580,441.0,E 52 St & 2 Ave,40.756014,-73.967416,3159.0,W 67 St & Broadway,40.774925,-73.982666,31290,Subscriber,1973,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955205,93,2019-12-31 23:58:18.0160,2019-12-31 23:59:51.6360,3141.0,1 Ave & E 68 St,40.765005,-73.958185,3142.0,1 Ave & E 62 St,40.761227,-73.960940,28734,Subscriber,1985,Female
955206,786,2019-12-31 23:58:59.8960,2020-01-01 00:12:06.3460,490.0,8 Ave & W 33 St,40.751551,-73.993934,513.0,W 56 St & 10 Ave,40.768254,-73.988639,41418,Subscriber,1991,Male
955207,351,2019-12-31 23:59:03.6950,2020-01-01 00:04:54.8730,3349.0,Grand Army Plaza & Plaza St West,40.672968,-73.970880,3368.0,5 Ave & 3 St,40.672815,-73.983524,27746,Subscriber,1935,Female
955208,1571,2019-12-31 23:59:21.3610,2020-01-01 00:25:32.9420,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,366.0,Clinton Ave & Myrtle Ave,40.693261,-73.968896,28506,Subscriber,1980,Male
955209,310,2019-12-31 23:59:55.2960,2020-01-01 00:05:05.7270,3351.0,E 102 St & 1 Ave,40.786995,-73.941648,3379.0,E 103 St & Lexington Ave,40.790305,-73.947558,21013,Subscriber,1969,Unknown

In [4]:
# Save the dataframe to a CSV file
df08.to_csv('data/citibike_complete.csv', index=False)